-- Script was generated by Devart dbForge Studio for MySQL, Version 6.0.622.0
-- Product home page: http://www.devart.com/dbforge/mysql/studio
-- Script date 07-Nov-15 8:26:43 PM
-- Server version: 5.6.26
-- Client version: 4.1

DROP DATABASE IF EXISTS test;
CREATE DATABASE test
CHARACTER SET latin1
COLLATE latin1_swedish_ci;

USE test;

CREATE TABLE company (
  id int(11) NOT NULL AUTO_INCREMENT,
  name varchar(50) DEFAULT NULL,
  address varchar(255) DEFAULT NULL,
  PRIMARY KEY (id)
)
ENGINE = INNODB
AUTO_INCREMENT = 1
CHARACTER SET latin1
COLLATE latin1_swedish_ci;

CREATE TABLE offers (
  id int(11) NOT NULL AUTO_INCREMENT,
  rules varchar(255) NOT NULL,
  name varchar(50) NOT NULL,
  PRIMARY KEY (id)
)
ENGINE = INNODB
AUTO_INCREMENT = 1
CHARACTER SET latin1
COLLATE latin1_swedish_ci;

CREATE TABLE users_adspace (
  user_id int(11) NOT NULL AUTO_INCREMENT,
  email varchar(50) NOT NULL,
  name varchar(50) DEFAULT NULL,
  lastname varchar(50) DEFAULT NULL,
  points int(11) NOT NULL DEFAULT 0,
  password varchar(255) NOT NULL,
  PRIMARY KEY (user_id)
)
ENGINE = INNODB
AUTO_INCREMENT = 6
AVG_ROW_LENGTH = 3276
CHARACTER SET latin1
COLLATE latin1_swedish_ci;

CREATE TABLE company_offer (
  company_ID int(11) NOT NULL,
  offer_ID int(11) DEFAULT NULL,
  CONSTRAINT FK_company_offer_company_id FOREIGN KEY (company_ID)
  REFERENCES company (id) ON DELETE RESTRICT ON UPDATE RESTRICT,
  CONSTRAINT FK_company_offer_offers_id FOREIGN KEY (offer_ID)
  REFERENCES offers (id) ON DELETE RESTRICT ON UPDATE RESTRICT
)
ENGINE = INNODB
CHARACTER SET latin1
COLLATE latin1_swedish_ci;

CREATE TABLE user_offers (
  user_ID int(11) NOT NULL,
  offer_ID int(11) NOT NULL,
  CONSTRAINT FK_user_offers_offers_id FOREIGN KEY (offer_ID)
  REFERENCES offers (id) ON DELETE RESTRICT ON UPDATE RESTRICT,
  CONSTRAINT FK_user_offers_users_adspace_user_id FOREIGN KEY (user_ID)
  REFERENCES users_adspace (user_id) ON DELETE RESTRICT ON UPDATE RESTRICT
)
ENGINE = INNODB
CHARACTER SET latin1
COLLATE latin1_swedish_ci;